#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from first.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "first.y"

#include<bits/stdc++.h>
using namespace std;
int tempCounter=0;
int labelCounter=0;
struct tableStructure
{
	string place;
	string code;
	string begin;
	string after;
}table[10000];


bool checkTypeCompatibility(string s1,string s2)
{
	if(s1=="BOOL"&&(s2=="UINT"||s2=="INT"))
	{
		return false;
	}
	
	if(s2=="BOOL"&&(s1=="UINT"||s1=="INT"))
	{
		return false;
	}
	return true;
}
void yyerror(const char *str)
{
	cout<<"\nError : \n"<<str<<endl;
}
int yylex();
int firstIndex=0;

string newtemp()
{
	string temp="t"+to_string(tempCounter);
	tempCounter++;
	return temp;
}

map<string,string >symbolTable;

string getLabel()
{
	string temp="L"+to_string(labelCounter);
	labelCounter++;
	return temp;
}


int getFreeIndex()
{
	table[firstIndex].place="";
	table[firstIndex].code="";
	table[firstIndex].begin="";
	table[firstIndex].after="";
	return firstIndex++;
}
int mainTableIndex=-1;


#line 64 "first.y"
typedef union
{
int number;
char* str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUM	258
#define	ID	259
#define	EOL	260
#define	INT	261
#define	UINT	262
#define	BOOL	263
#define	TR	264
#define	FL	265
#define	IF	266
#define	WHILE	267
#define	IFX	268
#define	ELSE	269
#define	PLEQ	270
#define	SBEQ	271
#define	MLEQ	272
#define	DVEQ	273
#define	GREQ	274
#define	LSEQ	275
#define	GRTH	276
#define	LSTH	277
#define	EQEQ	278
#define	NOTEQ	279
#define	LOR	280
#define	LNOT	281
#define	LAND	282


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUM;
static const int ID;
static const int EOL;
static const int INT;
static const int UINT;
static const int BOOL;
static const int TR;
static const int FL;
static const int IF;
static const int WHILE;
static const int IFX;
static const int ELSE;
static const int PLEQ;
static const int SBEQ;
static const int MLEQ;
static const int DVEQ;
static const int GREQ;
static const int LSEQ;
static const int GRTH;
static const int LSTH;
static const int EQEQ;
static const int NOTEQ;
static const int LOR;
static const int LNOT;
static const int LAND;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUM=258
	,ID=259
	,EOL=260
	,INT=261
	,UINT=262
	,BOOL=263
	,TR=264
	,FL=265
	,IF=266
	,WHILE=267
	,IFX=268
	,ELSE=269
	,PLEQ=270
	,SBEQ=271
	,MLEQ=272
	,DVEQ=273
	,GREQ=274
	,LSEQ=275
	,GRTH=276
	,LSTH=277
	,EQEQ=278
	,NOTEQ=279
	,LOR=280
	,LNOT=281
	,LAND=282


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUM=258;
const int YY_parse_CLASS::ID=259;
const int YY_parse_CLASS::EOL=260;
const int YY_parse_CLASS::INT=261;
const int YY_parse_CLASS::UINT=262;
const int YY_parse_CLASS::BOOL=263;
const int YY_parse_CLASS::TR=264;
const int YY_parse_CLASS::FL=265;
const int YY_parse_CLASS::IF=266;
const int YY_parse_CLASS::WHILE=267;
const int YY_parse_CLASS::IFX=268;
const int YY_parse_CLASS::ELSE=269;
const int YY_parse_CLASS::PLEQ=270;
const int YY_parse_CLASS::SBEQ=271;
const int YY_parse_CLASS::MLEQ=272;
const int YY_parse_CLASS::DVEQ=273;
const int YY_parse_CLASS::GREQ=274;
const int YY_parse_CLASS::LSEQ=275;
const int YY_parse_CLASS::GRTH=276;
const int YY_parse_CLASS::LSTH=277;
const int YY_parse_CLASS::EQEQ=278;
const int YY_parse_CLASS::NOTEQ=279;
const int YY_parse_CLASS::LOR=280;
const int YY_parse_CLASS::LNOT=281;
const int YY_parse_CLASS::LAND=282;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		102
#define	YYFLAG		-32768
#define	YYNTBASE	43

#define YYTRANSLATE(x) ((unsigned)(x) <= 282 ? yytranslate[x] : 50)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    37,    30,     2,    40,
    41,    35,    33,     2,    34,     2,    36,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    42,     2,
    32,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    29,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    38,    28,    39,    31,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     6,     8,    10,    12,    16,    22,    30,
    36,    40,    46,    50,    56,    60,    66,    72,    77,    82,
    87,    92,    97,   101,   105,   109,   112,   116,   120,   124,
   128,   132,   136,   140,   144,   148,   152,   156,   160,   164,
   167,   171,   173,   175,   177
};

static const short yyrhs[] = {    -1,
    43,    44,     0,    47,     0,    48,     0,    45,     0,    46,
     0,    38,    43,    39,     0,    11,    40,    49,    41,    44,
     0,    11,    40,    49,    41,    44,    14,    44,     0,    12,
    40,    49,    41,    44,     0,     6,     4,    42,     0,     6,
     4,    32,    49,    42,     0,     7,     4,    42,     0,     7,
     4,    32,    49,    42,     0,     8,     4,    42,     0,     8,
     4,    32,     9,    42,     0,     8,     4,    32,    10,    42,
     0,     4,    32,    49,    42,     0,     4,    15,    49,    42,
     0,     4,    16,    49,    42,     0,     4,    17,    49,    42,
     0,     4,    18,    49,    42,     0,    49,    28,    49,     0,
    49,    30,    49,     0,    49,    29,    49,     0,    31,    49,
     0,    49,    33,    49,     0,    49,    34,    49,     0,    49,
    35,    49,     0,    49,    36,    49,     0,    49,    37,    49,
     0,    49,    25,    49,     0,    49,    27,    49,     0,    49,
    19,    49,     0,    49,    20,    49,     0,    49,    21,    49,
     0,    49,    22,    49,     0,    49,    23,    49,     0,    49,
    24,    49,     0,    26,    49,     0,    40,    49,    41,     0,
     4,     0,     9,     0,    10,     0,     3,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   103,   106,   113,   119,   122,   125,   128,   136,   149,   165,
   183,   196,   210,   222,   235,   247,   260,   276,   295,   309,
   323,   338,   357,   379,   400,   421,   442,   463,   486,   508,
   530,   551,   565,   578,   590,   603,   616,   629,   641,   655,
   670,   679,   692,   700,   708
};

static const char * const yytname[] = {   "$","error","$illegal.","NUM","ID",
"EOL","INT","UINT","BOOL","TR","FL","IF","WHILE","IFX","ELSE","PLEQ","SBEQ",
"MLEQ","DVEQ","GREQ","LSEQ","GRTH","LSTH","EQEQ","NOTEQ","LOR","LNOT","LAND",
"'|'","'^'","'&'","'~'","'='","'+'","'-'","'*'","'/'","'%'","'{'","'}'","'('",
"')'","';'","program","statements","if_stmt","while_stmt","declare_stmt","assignment_stmt",
"exp",""
};
#endif

static const short yyr1[] = {     0,
    43,    43,    44,    44,    44,    44,    44,    45,    45,    46,
    47,    47,    47,    47,    47,    47,    47,    48,    48,    48,
    48,    48,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,    49
};

static const short yyr2[] = {     0,
     0,     2,     1,     1,     1,     1,     3,     5,     7,     5,
     3,     5,     3,     5,     3,     5,     5,     4,     4,     4,
     4,     4,     3,     3,     3,     2,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     2,
     3,     1,     1,     1,     1
};

static const short yydefact[] = {     1,
     0,     0,     0,     0,     0,     0,     0,     1,     2,     5,
     6,     3,     4,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    45,    42,    43,    44,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    11,     0,    13,
     0,    15,     0,     0,     7,    40,    26,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    19,    20,    21,    22,    18,     0,
     0,     0,     0,     0,     0,    41,    34,    35,    36,    37,
    38,    39,    32,    33,    23,    25,    24,    27,    28,    29,
    30,    31,    12,    14,    16,    17,     8,    10,     0,     9,
     0,     0
};

static const short yydefgoto[] = {     1,
     9,    10,    11,    12,    13,    32
};

static const short yypact[] = {-32768,
    19,   110,     2,     5,    13,    -8,    -7,-32768,-32768,-32768,
-32768,-32768,-32768,    49,    49,    49,    49,    49,   -22,   -21,
   -14,    49,    49,    56,-32768,-32768,-32768,-32768,    49,    49,
    49,    63,    87,   111,   135,   159,    49,-32768,    49,-32768,
     3,-32768,   231,   254,-32768,   385,   417,   277,    49,    49,
    49,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    49,    49,    49,    49,-32768,-32768,-32768,-32768,-32768,   183,
   207,     8,     9,    65,    65,-32768,   299,   316,   332,   347,
   361,   374,   385,   395,   404,   412,   417,   114,   114,    17,
    17,-32768,-32768,-32768,-32768,-32768,    41,-32768,    65,-32768,
    61,-32768
};

static const short yypgoto[] = {    48,
   -70,-32768,-32768,-32768,-32768,   -15
};


#define	YYLAST		454


static const short yytable[] = {    33,
    34,    35,    36,    97,    98,    19,    43,    44,    20,    37,
    39,    72,    73,    46,    47,    48,    21,    41,   101,    38,
    40,    70,     2,    71,     3,     4,     5,    42,   100,     6,
     7,    22,    23,    77,    78,    79,    80,    81,    82,    83,
    84,    85,    86,    87,    88,    89,    90,    91,    92,    95,
    96,    25,    26,    64,    99,    24,     8,    27,    28,     2,
   102,     3,     4,     5,     0,     0,     6,     7,     2,     0,
     3,     4,     5,     0,    29,     6,     7,     0,     0,    30,
     0,    49,    50,    51,    52,    53,    54,    55,    31,    56,
    57,    58,    59,     8,    45,    60,    61,    62,    63,    64,
     0,     0,     8,     0,    65,    49,    50,    51,    52,    53,
    54,    55,     0,    56,    57,    58,    59,     0,     0,    60,
    61,    62,    63,    64,    14,    15,    16,    17,    66,    49,
    50,    51,    52,    53,    54,    55,     0,    56,    57,    58,
    59,    18,     0,    60,    61,    62,    63,    64,    62,    63,
    64,     0,    67,    49,    50,    51,    52,    53,    54,    55,
     0,    56,    57,    58,    59,     0,     0,    60,    61,    62,
    63,    64,     0,     0,     0,     0,    68,    49,    50,    51,
    52,    53,    54,    55,     0,    56,    57,    58,    59,     0,
     0,    60,    61,    62,    63,    64,     0,     0,     0,     0,
    69,    49,    50,    51,    52,    53,    54,    55,     0,    56,
    57,    58,    59,     0,     0,    60,    61,    62,    63,    64,
     0,     0,     0,     0,    93,    49,    50,    51,    52,    53,
    54,    55,     0,    56,    57,    58,    59,     0,     0,    60,
    61,    62,    63,    64,     0,     0,     0,     0,    94,    49,
    50,    51,    52,    53,    54,    55,     0,    56,    57,    58,
    59,     0,     0,    60,    61,    62,    63,    64,     0,     0,
     0,    74,    49,    50,    51,    52,    53,    54,    55,     0,
    56,    57,    58,    59,     0,     0,    60,    61,    62,    63,
    64,     0,     0,     0,    75,    49,    50,    51,    52,    53,
    54,    55,     0,    56,    57,    58,    59,     0,     0,    60,
    61,    62,    63,    64,     0,     0,     0,    76,    50,    51,
    52,    53,    54,    55,     0,    56,    57,    58,    59,     0,
     0,    60,    61,    62,    63,    64,    51,    52,    53,    54,
    55,     0,    56,    57,    58,    59,     0,     0,    60,    61,
    62,    63,    64,    52,    53,    54,    55,     0,    56,    57,
    58,    59,     0,     0,    60,    61,    62,    63,    64,    53,
    54,    55,     0,    56,    57,    58,    59,     0,     0,    60,
    61,    62,    63,    64,    54,    55,     0,    56,    57,    58,
    59,     0,     0,    60,    61,    62,    63,    64,    55,     0,
    56,    57,    58,    59,     0,     0,    60,    61,    62,    63,
    64,    56,    57,    58,    59,     0,     0,    60,    61,    62,
    63,    64,    57,    58,    59,     0,     0,    60,    61,    62,
    63,    64,    58,    59,     0,     0,    60,    61,    62,    63,
    64,    59,     0,     0,    60,    61,    62,    63,    64,    60,
    61,    62,    63,    64
};

static const short yycheck[] = {    15,
    16,    17,    18,    74,    75,     4,    22,    23,     4,    32,
    32,     9,    10,    29,    30,    31,     4,    32,     0,    42,
    42,    37,     4,    39,     6,     7,     8,    42,    99,    11,
    12,    40,    40,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    42,
    42,     3,     4,    37,    14,     8,    38,     9,    10,     4,
     0,     6,     7,     8,    -1,    -1,    11,    12,     4,    -1,
     6,     7,     8,    -1,    26,    11,    12,    -1,    -1,    31,
    -1,    19,    20,    21,    22,    23,    24,    25,    40,    27,
    28,    29,    30,    38,    39,    33,    34,    35,    36,    37,
    -1,    -1,    38,    -1,    42,    19,    20,    21,    22,    23,
    24,    25,    -1,    27,    28,    29,    30,    -1,    -1,    33,
    34,    35,    36,    37,    15,    16,    17,    18,    42,    19,
    20,    21,    22,    23,    24,    25,    -1,    27,    28,    29,
    30,    32,    -1,    33,    34,    35,    36,    37,    35,    36,
    37,    -1,    42,    19,    20,    21,    22,    23,    24,    25,
    -1,    27,    28,    29,    30,    -1,    -1,    33,    34,    35,
    36,    37,    -1,    -1,    -1,    -1,    42,    19,    20,    21,
    22,    23,    24,    25,    -1,    27,    28,    29,    30,    -1,
    -1,    33,    34,    35,    36,    37,    -1,    -1,    -1,    -1,
    42,    19,    20,    21,    22,    23,    24,    25,    -1,    27,
    28,    29,    30,    -1,    -1,    33,    34,    35,    36,    37,
    -1,    -1,    -1,    -1,    42,    19,    20,    21,    22,    23,
    24,    25,    -1,    27,    28,    29,    30,    -1,    -1,    33,
    34,    35,    36,    37,    -1,    -1,    -1,    -1,    42,    19,
    20,    21,    22,    23,    24,    25,    -1,    27,    28,    29,
    30,    -1,    -1,    33,    34,    35,    36,    37,    -1,    -1,
    -1,    41,    19,    20,    21,    22,    23,    24,    25,    -1,
    27,    28,    29,    30,    -1,    -1,    33,    34,    35,    36,
    37,    -1,    -1,    -1,    41,    19,    20,    21,    22,    23,
    24,    25,    -1,    27,    28,    29,    30,    -1,    -1,    33,
    34,    35,    36,    37,    -1,    -1,    -1,    41,    20,    21,
    22,    23,    24,    25,    -1,    27,    28,    29,    30,    -1,
    -1,    33,    34,    35,    36,    37,    21,    22,    23,    24,
    25,    -1,    27,    28,    29,    30,    -1,    -1,    33,    34,
    35,    36,    37,    22,    23,    24,    25,    -1,    27,    28,
    29,    30,    -1,    -1,    33,    34,    35,    36,    37,    23,
    24,    25,    -1,    27,    28,    29,    30,    -1,    -1,    33,
    34,    35,    36,    37,    24,    25,    -1,    27,    28,    29,
    30,    -1,    -1,    33,    34,    35,    36,    37,    25,    -1,
    27,    28,    29,    30,    -1,    -1,    33,    34,    35,    36,
    37,    27,    28,    29,    30,    -1,    -1,    33,    34,    35,
    36,    37,    28,    29,    30,    -1,    -1,    33,    34,    35,
    36,    37,    29,    30,    -1,    -1,    33,    34,    35,    36,
    37,    30,    -1,    -1,    33,    34,    35,    36,    37,    33,
    34,    35,    36,    37
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 103 "first.y"
{
								yyval.number=getFreeIndex();		
							;
    break;}
case 2:
#line 106 "first.y"
{
 								yyval.number=getFreeIndex();
 								table[yyval.number].code=table[yyvsp[0].number].code;
 								mainTableIndex = yyval.number;
 								cout<<table[mainTableIndex].code<<endl;
 							;
    break;}
case 3:
#line 115 "first.y"
{
								yyval.number = yyvsp[0].number;
							;
    break;}
case 4:
#line 119 "first.y"
{yyval.number = yyvsp[0].number;
							;
    break;}
case 5:
#line 122 "first.y"
{yyval.number = yyvsp[0].number;
                            ;
    break;}
case 6:
#line 125 "first.y"
{yyval.number = yyvsp[0].number;
                            ;
    break;}
case 7:
#line 128 "first.y"
{
								yyval.number=yyvsp[-1].number;
								mainTableIndex=yyval.number;							
							;
    break;}
case 8:
#line 136 "first.y"
{
  									if(symbolTable[table[yyvsp[-2].number].place]!="BOOL")
									{
										cout<<"Not bool type"<<endl;
										exit(0);
									}
									yyval.number=getFreeIndex();
									table[yyval.number].after=getLabel();
									string gen="";
									gen="if "+table[yyvsp[-2].number].place+"=="+'0'+" goto "+table[yyval.number].after+'\n';
									table[yyval.number].code=table[yyvsp[-2].number].code+gen+table[yyvsp[0].number].code+'\n'+table[yyval.number].after;
									mainTableIndex==yyval.number;		
  								 ;
    break;}
case 9:
#line 149 "first.y"
{
  									if(symbolTable[table[yyvsp[-4].number].place]!="BOOL")
									{
										cout<<"Not bool type"<<endl;
										exit(0);
									}
									yyval.number=getFreeIndex();
									table[yyval.number].after=getLabel();
									string gen="";
									gen="if "+table[yyvsp[-4].number].place+"=="+'0'+" goto "+table[yyval.number].after+'\n';
									table[yyval.number].code=table[yyvsp[-4].number].code+gen+table[yyvsp[-2].number].code+'\n'+table[yyval.number].after;
									mainTableIndex==yyval.number;
  								;
    break;}
case 10:
#line 166 "first.y"
{
									if(symbolTable[table[yyvsp[-2].number].place]!="BOOL")
									{
										cout<<"Not bool type"<<endl;
										exit(0);
									}
									yyval.number=getFreeIndex();
									table[yyval.number].begin=getLabel();
									table[yyval.number].after=getLabel();
									string gen="";
									
									gen=table[yyval.number].begin+":\n"+"if "+table[yyvsp[-2].number].place+"=="+'0'+" goto "+table[yyval.number].after+'\n';
									table[yyval.number].code=table[yyvsp[-2].number].code+gen+table[yyvsp[0].number].code+'\n'+"goto " +table[yyval.number].begin+"\n"+table[yyval.number].after+":";
									mainTableIndex==yyval.number;

							;
    break;}
case 11:
#line 184 "first.y"
{
							if(symbolTable.find(string(yyvsp[-1].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
							symbolTable[string(yyvsp[-1].str)] = "INT";
							yyval.number =getFreeIndex();
							table[yyval.number].code ="Declaring "+string(yyvsp[-1].str);
							mainTableIndex=yyval.number;
     		            ;
    break;}
case 12:
#line 196 "first.y"
{
    
    						if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
    						symbolTable[string(yyvsp[-3].str)] = "INT";
    						yyval.number =getFreeIndex();
							string mycode  = string(yyvsp[-3].str)+ '=' + table[yyvsp[-1].number].place + '\n';
							table[yyval.number].code=table[yyvsp[-1].number].code+"\n"+mycode;
							mainTableIndex=yyval.number;
    				    ;
    break;}
case 13:
#line 210 "first.y"
{
    						if(symbolTable.find(string(yyvsp[-1].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-1].str)] = "UINT";
	 						yyval.number =getFreeIndex();
							table[yyval.number].code ="Declaring "+string(yyvsp[-1].str);
							mainTableIndex=yyval.number;
     		            ;
    break;}
case 14:
#line 222 "first.y"
{
    						if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
        					symbolTable[string(yyvsp[-3].str)] = "UINT";
    						yyval.number =getFreeIndex();
							string mycode  = string(yyvsp[-3].str)+ '=' + table[yyvsp[-1].number].place + '\n';
							table[yyval.number].code=table[yyvsp[-1].number].code+"\n"+mycode;
							mainTableIndex=yyval.number;
    				    ;
    break;}
case 15:
#line 235 "first.y"
{
                            if(symbolTable.find(string(yyvsp[-1].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-1].str)] = "BOOL";
	 						yyval.number =getFreeIndex();
							table[yyval.number].code ="Declaring "+string(yyvsp[-1].str);
							mainTableIndex=yyval.number;
   						;
    break;}
case 16:
#line 247 "first.y"
{
                            if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-3].str)] = "BOOL";
	 						yyval.number =getFreeIndex();
							string mycode  = "Declared and Initialised  "+string(yyvsp[-3].str)+ '=' + "true" + '\n';
							table[yyval.number].code =mycode;
							mainTableIndex=yyval.number;
   						   ;
    break;}
case 17:
#line 260 "first.y"
{
                            if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-3].str)] = "BOOL";
	 						yyval.number =getFreeIndex();
							string mycode  = "Declared and Initialised"+ string(yyvsp[-3].str)+ '=' + "false" + '\n';
							table[yyval.number].code =mycode;
							mainTableIndex=yyval.number;
   						   ;
    break;}
case 18:
#line 278 "first.y"
{
					if(symbolTable.find(string(yyvsp[-3].str))==symbolTable.end())
					{
						cout<<"Undeclared ID Compiler Error\n";
						exit(0);
					}
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					yyval.number =getFreeIndex();
					string mycode  = string(yyvsp[-3].str)+ '=' + table[yyvsp[-1].number].place + '\n';
					table[yyval.number].code=table[yyvsp[-1].number].code+mycode;
					mainTableIndex=yyval.number;
					;
    break;}
case 19:
#line 295 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '+' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;
					//cout<<table[mainTableIndex].code<<endl;
			      ;
    break;}
case 20:
#line 309 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '-' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;

			      ;
    break;}
case 21:
#line 323 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '*' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;
					//cout<<table[mainTableIndex].code<<endl;
			      ;
    break;}
case 22:
#line 338 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '/' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;
			      ;
    break;}
case 23:
#line 358 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{	
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '|' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			     ;
    break;}
case 24:
#line 379 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '&' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 25:
#line 400 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '^' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
				  ;
    break;}
case 26:
#line 421 "first.y"
{
	  				yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[0].number].place]=="BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place]=="INT")
					{
						symbolTable[table[yyval.number].place] ="INT";
					}
					else
					{
						symbolTable[table[yyval.number].place] ="UINT";
					}
					string mygen = '~' + table[yyvsp[0].number].place+"\n";
					table[yyval.number].code = table[yyvsp[0].number].code+table[yyval.number].place + '=' + mygen;
					mainTableIndex=yyval.number;
				  ;
    break;}
case 27:
#line 442 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '+' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 28:
#line 463 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '-' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 29:
#line 486 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '*' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 30:
#line 508 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '/' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 31:
#line 530 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '%' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 32:
#line 551 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp(); 
					if(symbolTable[table[yyvsp[-2].number].place] !="BOOL"||symbolTable[table[yyvsp[0].number].place] !="BOOL")
					{
						cout<<"IncompatibleType\n";
						exit(0);
					}
					
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "||" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 33:
#line 565 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] !="BOOL"||symbolTable[table[yyvsp[0].number].place] !="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "&&" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 34:
#line 578 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + ">=" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 35:
#line 590 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "<=" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 36:
#line 603 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + ">" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 37:
#line 616 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "<" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 38:
#line 629 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "==" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 39:
#line 641 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "!=" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 40:
#line 655 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[0].number].place] !="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[0].number].code +table[yyval.number].place + '=' + "!" + table[yyvsp[0].number].place +"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 41:
#line 670 "first.y"
{
					yyval.number = getFreeIndex();
					table[yyval.number] = table[yyvsp[-1].number];
					mainTableIndex = yyval.number;
				  ;
    break;}
case 42:
#line 679 "first.y"
{
	                if(symbolTable.find(string(yyvsp[0].str))==symbolTable.end())
					{
						cout<<"Undeclared ID Compiler Error\n";
						exit(0);
					}
	    			yyval.number =getFreeIndex();
					table[yyval.number].place =string(yyvsp[0].str);
					mainTableIndex=yyval.number;
				  ;
    break;}
case 43:
#line 692 "first.y"
{
	    			yyval.number = getFreeIndex();
					table[yyval.number].place = newtemp();
					symbolTable[table[yyval.number].place]="BOOL";
					table[yyval.number].code = table[yyval.number].place + " = " + "true" + "\n";
					mainTableIndex = yyval.number;
				  ;
    break;}
case 44:
#line 700 "first.y"
{
	    			yyval.number = getFreeIndex();
					table[yyval.number].place = newtemp();
					symbolTable[table[yyval.number].place]="BOOL";
					table[yyval.number].code = table[yyval.number].place + " = " + "false" + "\n";
					mainTableIndex = yyval.number;
				  ;
    break;}
case 45:
#line 708 "first.y"
{
	
						yyval.number = getFreeIndex();
						table[yyval.number].place = newtemp();
						symbolTable[table[yyval.number].place]="INT";
						table[yyval.number].code = table[yyval.number].place + " = " + string(yyvsp[0].str) + "\n";
						mainTableIndex = yyval.number;
				  ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 721 "first.y"




int main()
{
	yyparse();
	cout<<"\n\nGenerated 3-address code : \n\n";

	return 0;
}
