#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from first.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "first.y"

#include<bits/stdc++.h>
using namespace std;
int tempCounter=0;
int labelCounter=0;
struct tableStructure
{
	string place;
	string code;
	string begin;
	string after;
}table[10000];


bool checkTypeCompatibility(string s1,string s2)
{
	if(s1=="BOOL"&&(s2=="UINT"||s2=="INT"))
	{
		return false;
	}
	
	if(s2=="BOOL"&&(s1=="UINT"||s1=="INT"))
	{
		return false;
	}
	return true;
}
void yyerror(char *str)
{
	cout<<"\nError : \n"<<str<<endl;
}
int yylex();
int firstIndex=0;

string newtemp()
{
	string temp="t"+to_string(tempCounter);
	tempCounter++;
	return temp;
}

map<string,string >symbolTable;

string getLabel()
{
	string temp="L"+to_string(tempCounter);
	labelCounter++;
	return temp;
}


int getFreeIndex()
{
	table[firstIndex].place="";
	table[firstIndex].code="";
	table[firstIndex].begin="";
	table[firstIndex].after="";
	return firstIndex++;
}
int mainTableIndex=-1;


#line 64 "first.y"
typedef union
{
int number;
char* str;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUM	258
#define	ID	259
#define	EOL	260
#define	INT	261
#define	UINT	262
#define	BOOL	263
#define	TR	264
#define	FL	265
#define	IF	266
#define	ELSE	267
#define	PLEQ	268
#define	SBEQ	269
#define	MLEQ	270
#define	DVEQ	271
#define	GREQ	272
#define	LSEQ	273
#define	GRTH	274
#define	LSTH	275
#define	EQEQ	276
#define	NOTEQ	277
#define	LOR	278
#define	LNOT	279
#define	LAND	280


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUM;
static const int ID;
static const int EOL;
static const int INT;
static const int UINT;
static const int BOOL;
static const int TR;
static const int FL;
static const int IF;
static const int ELSE;
static const int PLEQ;
static const int SBEQ;
static const int MLEQ;
static const int DVEQ;
static const int GREQ;
static const int LSEQ;
static const int GRTH;
static const int LSTH;
static const int EQEQ;
static const int NOTEQ;
static const int LOR;
static const int LNOT;
static const int LAND;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUM=258
	,ID=259
	,EOL=260
	,INT=261
	,UINT=262
	,BOOL=263
	,TR=264
	,FL=265
	,IF=266
	,ELSE=267
	,PLEQ=268
	,SBEQ=269
	,MLEQ=270
	,DVEQ=271
	,GREQ=272
	,LSEQ=273
	,GRTH=274
	,LSTH=275
	,EQEQ=276
	,NOTEQ=277
	,LOR=278
	,LNOT=279
	,LAND=280


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUM=258;
const int YY_parse_CLASS::ID=259;
const int YY_parse_CLASS::EOL=260;
const int YY_parse_CLASS::INT=261;
const int YY_parse_CLASS::UINT=262;
const int YY_parse_CLASS::BOOL=263;
const int YY_parse_CLASS::TR=264;
const int YY_parse_CLASS::FL=265;
const int YY_parse_CLASS::IF=266;
const int YY_parse_CLASS::ELSE=267;
const int YY_parse_CLASS::PLEQ=268;
const int YY_parse_CLASS::SBEQ=269;
const int YY_parse_CLASS::MLEQ=270;
const int YY_parse_CLASS::DVEQ=271;
const int YY_parse_CLASS::GREQ=272;
const int YY_parse_CLASS::LSEQ=273;
const int YY_parse_CLASS::GRTH=274;
const int YY_parse_CLASS::LSTH=275;
const int YY_parse_CLASS::EQEQ=276;
const int YY_parse_CLASS::NOTEQ=277;
const int YY_parse_CLASS::LOR=278;
const int YY_parse_CLASS::LNOT=279;
const int YY_parse_CLASS::LAND=280;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		108
#define	YYFLAG		-32768
#define	YYNTBASE	41

#define YYTRANSLATE(x) ((unsigned)(x) <= 280 ? yytranslate[x] : 47)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    35,    28,     2,    36,
    37,    33,    31,     2,    32,     2,    34,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    40,     2,
    30,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    27,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    38,    26,    39,    29,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     5,     6,     9,    12,    15,    34,    45,    49,
    55,    59,    65,    69,    75,    81,    86,    91,    96,   101,
   106,   110,   114,   118,   121,   125,   129,   133,   137,   141,
   145,   149,   153,   157,   161,   165,   169,   173,   176,   180,
   182,   184,   186
};

static const short yyrhs[] = {    -1,
    41,    42,     5,     0,     0,    44,    42,     0,    45,    42,
     0,    43,    42,     0,    11,    36,    46,    37,     5,    38,
     5,    42,     5,    39,     5,    12,     5,    38,     5,    42,
     5,    39,     0,    11,    36,    46,    37,     5,    38,     5,
    42,     5,    39,     0,     6,     4,    40,     0,     6,     4,
    30,    46,    40,     0,     7,     4,    40,     0,     7,     4,
    30,    46,    40,     0,     8,     4,    40,     0,     8,     4,
    30,     9,    40,     0,     8,     4,    30,    10,    40,     0,
     4,    30,    46,    40,     0,     4,    13,    46,    40,     0,
     4,    14,    46,    40,     0,     4,    15,    46,    40,     0,
     4,    16,    46,    40,     0,    46,    26,    46,     0,    46,
    28,    46,     0,    46,    27,    46,     0,    29,    46,     0,
    46,    31,    46,     0,    46,    32,    46,     0,    46,    33,
    46,     0,    46,    34,    46,     0,    46,    35,    46,     0,
    46,    23,    46,     0,    46,    25,    46,     0,    46,    17,
    46,     0,    46,    18,    46,     0,    46,    19,    46,     0,
    46,    20,    46,     0,    46,    21,    46,     0,    46,    22,
    46,     0,    24,    46,     0,    36,    46,    37,     0,     4,
     0,     9,     0,    10,     0,     3,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   101,   102,   107,   110,   116,   122,   131,   136,   158,   171,
   185,   197,   210,   222,   235,   251,   270,   284,   298,   313,
   332,   354,   375,   396,   417,   438,   461,   483,   505,   526,
   540,   553,   565,   578,   591,   604,   616,   630,   645,   654,
   667,   675,   683
};

static const char * const yytname[] = {   "$","error","$illegal.","NUM","ID",
"EOL","INT","UINT","BOOL","TR","FL","IF","ELSE","PLEQ","SBEQ","MLEQ","DVEQ",
"GREQ","LSEQ","GRTH","LSTH","EQEQ","NOTEQ","LOR","LNOT","LAND","'|'","'^'","'&'",
"'~'","'='","'+'","'-'","'*'","'/'","'%'","'('","')'","'{'","'}'","';'","program",
"statements","if_stmt","declare_stmt","assignment_stmt","exp",""
};
#endif

static const short yyr1[] = {     0,
    41,    41,    42,    42,    42,    42,    43,    43,    44,    44,
    44,    44,    44,    44,    44,    45,    45,    45,    45,    45,
    46,    46,    46,    46,    46,    46,    46,    46,    46,    46,
    46,    46,    46,    46,    46,    46,    46,    46,    46,    46,
    46,    46,    46
};

static const short yyr2[] = {     0,
     0,     3,     0,     2,     2,     2,    18,    10,     3,     5,
     3,     5,     3,     5,     5,     4,     4,     4,     4,     4,
     3,     3,     3,     2,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     2,     3,     1,
     1,     1,     1
};

static const short yydefact[] = {     1,
     3,     0,     0,     0,     0,     0,     0,     3,     3,     3,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     2,
     6,     4,     5,    43,    40,    41,    42,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     9,     0,    11,     0,
    13,     0,    38,    24,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,    17,    18,    19,    20,    16,     0,     0,     0,     0,
     0,    39,    32,    33,    34,    35,    36,    37,    30,    31,
    21,    23,    22,    25,    26,    27,    28,    29,    10,    12,
    14,    15,     0,     0,     3,     0,     0,     8,     0,     0,
     0,     0,     3,     0,     0,     7,     0,     0
};

static const short yydefgoto[] = {     1,
     7,     8,     9,    10,    31
};

static const short yypact[] = {-32768,
   378,    -2,     5,    12,    22,    19,    51,   414,   414,   414,
    50,    50,    50,    50,    50,   -23,   -22,   -15,    50,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    50,    50,    50,
    71,    95,   119,   143,   167,    50,-32768,    50,-32768,    26,
-32768,   239,   365,    -1,   260,    50,    50,    50,    50,    50,
    50,    50,    50,    50,    50,    50,    50,    50,    50,    50,
    50,-32768,-32768,-32768,-32768,-32768,   191,   215,    17,    18,
    57,-32768,   280,   297,   313,   328,   342,    38,   365,    49,
   374,   382,    -1,   -11,   -11,    32,    32,-32768,-32768,-32768,
-32768,-32768,    30,    73,   414,    80,    61,    96,    97,   102,
    70,   105,   414,   114,    85,-32768,   125,-32768
};

static const short yypgoto[] = {-32768,
    -8,-32768,-32768,-32768,    -9
};


#define	YYLAST		425


static const short yytable[] = {    21,
    22,    23,    32,    33,    34,    35,    36,    38,    16,    42,
    11,    12,    13,    14,    40,    17,    37,    39,    43,    44,
    45,    59,    60,    61,    41,    18,    67,    15,    68,    57,
    58,    59,    60,    61,    69,    70,    73,    74,    75,    76,
    77,    78,    79,    80,    81,    82,    83,    84,    85,    86,
    87,    88,    24,    25,    19,    20,    91,    92,    26,    27,
    52,    93,    53,    54,    55,    56,    61,    94,    57,    58,
    59,    60,    61,    28,    54,    55,    56,    95,    29,    57,
    58,    59,    60,    61,    97,    30,    96,    46,    47,    48,
    49,    50,    51,    52,   104,    53,    54,    55,    56,    98,
    99,    57,    58,    59,    60,    61,   101,   102,   100,   103,
    62,    46,    47,    48,    49,    50,    51,    52,   105,    53,
    54,    55,    56,   106,   108,    57,    58,    59,    60,    61,
     0,     0,     0,     0,    63,    46,    47,    48,    49,    50,
    51,    52,     0,    53,    54,    55,    56,     0,     0,    57,
    58,    59,    60,    61,     0,     0,     0,     0,    64,    46,
    47,    48,    49,    50,    51,    52,     0,    53,    54,    55,
    56,     0,     0,    57,    58,    59,    60,    61,     0,     0,
     0,     0,    65,    46,    47,    48,    49,    50,    51,    52,
     0,    53,    54,    55,    56,     0,     0,    57,    58,    59,
    60,    61,     0,     0,     0,     0,    66,    46,    47,    48,
    49,    50,    51,    52,     0,    53,    54,    55,    56,     0,
     0,    57,    58,    59,    60,    61,     0,     0,     0,     0,
    89,    46,    47,    48,    49,    50,    51,    52,     0,    53,
    54,    55,    56,     0,     0,    57,    58,    59,    60,    61,
     0,     0,     0,     0,    90,    46,    47,    48,    49,    50,
    51,    52,     0,    53,    54,    55,    56,     0,     0,    57,
    58,    59,    60,    61,     0,    71,    46,    47,    48,    49,
    50,    51,    52,     0,    53,    54,    55,    56,     0,     0,
    57,    58,    59,    60,    61,     0,    72,    47,    48,    49,
    50,    51,    52,     0,    53,    54,    55,    56,     0,     0,
    57,    58,    59,    60,    61,    48,    49,    50,    51,    52,
     0,    53,    54,    55,    56,     0,     0,    57,    58,    59,
    60,    61,    49,    50,    51,    52,     0,    53,    54,    55,
    56,     0,     0,    57,    58,    59,    60,    61,    50,    51,
    52,     0,    53,    54,    55,    56,     0,     0,    57,    58,
    59,    60,    61,    51,    52,     0,    53,    54,    55,    56,
     0,     0,    57,    58,    59,    60,    61,   107,     0,     0,
     0,     2,     0,     3,     4,     5,     0,     0,     6,    53,
    54,    55,    56,     0,     0,    57,    58,    59,    60,    61,
    55,    56,     0,     0,    57,    58,    59,    60,    61,    56,
     0,     0,    57,    58,    59,    60,    61,     2,     0,     3,
     4,     5,     0,     0,     6
};

static const short yycheck[] = {     8,
     9,    10,    12,    13,    14,    15,    30,    30,     4,    19,
    13,    14,    15,    16,    30,     4,    40,    40,    28,    29,
    30,    33,    34,    35,    40,     4,    36,    30,    38,    31,
    32,    33,    34,    35,     9,    10,    46,    47,    48,    49,
    50,    51,    52,    53,    54,    55,    56,    57,    58,    59,
    60,    61,     3,     4,    36,     5,    40,    40,     9,    10,
    23,     5,    25,    26,    27,    28,    35,    38,    31,    32,
    33,    34,    35,    24,    26,    27,    28,     5,    29,    31,
    32,    33,    34,    35,     5,    36,    95,    17,    18,    19,
    20,    21,    22,    23,   103,    25,    26,    27,    28,    39,
     5,    31,    32,    33,    34,    35,     5,    38,    12,     5,
    40,    17,    18,    19,    20,    21,    22,    23,     5,    25,
    26,    27,    28,    39,     0,    31,    32,    33,    34,    35,
    -1,    -1,    -1,    -1,    40,    17,    18,    19,    20,    21,
    22,    23,    -1,    25,    26,    27,    28,    -1,    -1,    31,
    32,    33,    34,    35,    -1,    -1,    -1,    -1,    40,    17,
    18,    19,    20,    21,    22,    23,    -1,    25,    26,    27,
    28,    -1,    -1,    31,    32,    33,    34,    35,    -1,    -1,
    -1,    -1,    40,    17,    18,    19,    20,    21,    22,    23,
    -1,    25,    26,    27,    28,    -1,    -1,    31,    32,    33,
    34,    35,    -1,    -1,    -1,    -1,    40,    17,    18,    19,
    20,    21,    22,    23,    -1,    25,    26,    27,    28,    -1,
    -1,    31,    32,    33,    34,    35,    -1,    -1,    -1,    -1,
    40,    17,    18,    19,    20,    21,    22,    23,    -1,    25,
    26,    27,    28,    -1,    -1,    31,    32,    33,    34,    35,
    -1,    -1,    -1,    -1,    40,    17,    18,    19,    20,    21,
    22,    23,    -1,    25,    26,    27,    28,    -1,    -1,    31,
    32,    33,    34,    35,    -1,    37,    17,    18,    19,    20,
    21,    22,    23,    -1,    25,    26,    27,    28,    -1,    -1,
    31,    32,    33,    34,    35,    -1,    37,    18,    19,    20,
    21,    22,    23,    -1,    25,    26,    27,    28,    -1,    -1,
    31,    32,    33,    34,    35,    19,    20,    21,    22,    23,
    -1,    25,    26,    27,    28,    -1,    -1,    31,    32,    33,
    34,    35,    20,    21,    22,    23,    -1,    25,    26,    27,
    28,    -1,    -1,    31,    32,    33,    34,    35,    21,    22,
    23,    -1,    25,    26,    27,    28,    -1,    -1,    31,    32,
    33,    34,    35,    22,    23,    -1,    25,    26,    27,    28,
    -1,    -1,    31,    32,    33,    34,    35,     0,    -1,    -1,
    -1,     4,    -1,     6,     7,     8,    -1,    -1,    11,    25,
    26,    27,    28,    -1,    -1,    31,    32,    33,    34,    35,
    27,    28,    -1,    -1,    31,    32,    33,    34,    35,    28,
    -1,    -1,    31,    32,    33,    34,    35,     4,    -1,     6,
     7,     8,    -1,    -1,    11
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 2:
#line 102 "first.y"
{
 								mainTableIndex = yyvsp[-1].number;
 								cout<<table[mainTableIndex].code<<endl;
 							;
    break;}
case 3:
#line 107 "first.y"
{
							yyval.number =getFreeIndex();
						;
    break;}
case 4:
#line 110 "first.y"
{
								yyval.number=getFreeIndex();
								table[yyval.number].code = table[yyvsp[-1].number].code+"\n"+table[yyvsp[0].number].code;
								mainTableIndex=yyval.number;
							;
    break;}
case 5:
#line 116 "first.y"
{
								yyval.number=getFreeIndex();
								table[yyval.number].code = table[yyvsp[-1].number].code+"\n"+table[yyvsp[0].number].code;
								mainTableIndex=yyval.number;
							;
    break;}
case 6:
#line 122 "first.y"
{
								yyval.number=getFreeIndex();
								table[yyval.number].code = table[yyvsp[-1].number].code+"\n"+table[yyvsp[0].number].code;
								mainTableIndex=yyval.number;
							;
    break;}
case 7:
#line 133 "first.y"
{cout<<"Else\n";;
    break;}
case 8:
#line 136 "first.y"
{	
												yyval.number=getFreeIndex();
												
												table[yyval.number].after =getLabel();
												
												
												
												if(symbolTable[table[yyvsp[-7].number].place]!="BOOL")
												{
													cout<<"Incompatible Type\n";
													exit(0);
												}
												string gen = "if " + table[yyvsp[-7].number].place + "== " + "0" +" goto " + table[yyval.number].after+'\n';
												table[yyval.number].code = gen+table[yyvsp[-2].number].code+'\n';
												

											  ;
    break;}
case 9:
#line 159 "first.y"
{
							if(symbolTable.find(string(yyvsp[-1].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
							symbolTable[string(yyvsp[-1].str)] = "INT";
							yyval.number =getFreeIndex();
							table[yyval.number].code ="Declaring "+string(yyvsp[-1].str);
							mainTableIndex=yyval.number;
     		            ;
    break;}
case 10:
#line 171 "first.y"
{
    
    						if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
    						symbolTable[string(yyvsp[-3].str)] = "INT";
    						yyval.number =getFreeIndex();
							string mycode  = string(yyvsp[-3].str)+ '=' + table[yyvsp[-1].number].place + '\n';
							table[yyval.number].code=table[yyvsp[-1].number].code+"\n"+mycode;
							mainTableIndex=yyval.number;
    				    ;
    break;}
case 11:
#line 185 "first.y"
{
    						if(symbolTable.find(string(yyvsp[-1].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-1].str)] = "UINT";
	 						yyval.number =getFreeIndex();
							table[yyval.number].code ="Declaring "+string(yyvsp[-1].str);
							mainTableIndex=yyval.number;
     		            ;
    break;}
case 12:
#line 197 "first.y"
{
    						if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
        					symbolTable[string(yyvsp[-3].str)] = "UINT";
    						yyval.number =getFreeIndex();
							string mycode  = string(yyvsp[-3].str)+ '=' + table[yyvsp[-1].number].place + '\n';
							table[yyval.number].code=table[yyvsp[-1].number].code+"\n"+mycode;
							mainTableIndex=yyval.number;
    				    ;
    break;}
case 13:
#line 210 "first.y"
{
                            if(symbolTable.find(string(yyvsp[-1].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-1].str)] = "BOOL";
	 						yyval.number =getFreeIndex();
							table[yyval.number].code ="Declaring "+string(yyvsp[-1].str);
							mainTableIndex=yyval.number;
   						;
    break;}
case 14:
#line 222 "first.y"
{
                            if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-3].str)] = "BOOL";
	 						yyval.number =getFreeIndex();
							string mycode  = "Declared and Initialised  "+string(yyvsp[-3].str)+ '=' + "true" + '\n';
							table[yyval.number].code =mycode;
							mainTableIndex=yyval.number;
   						   ;
    break;}
case 15:
#line 235 "first.y"
{
                            if(symbolTable.find(string(yyvsp[-3].str))!=symbolTable.end())
							{
								cout<<"Redeclared ID Compiler Error\n";
								exit(0);
							}
	 						symbolTable[string(yyvsp[-3].str)] = "BOOL";
	 						yyval.number =getFreeIndex();
							string mycode  = "Declared and Initialised"+ string(yyvsp[-3].str)+ '=' + "false" + '\n';
							table[yyval.number].code =mycode;
							mainTableIndex=yyval.number;
   						   ;
    break;}
case 16:
#line 253 "first.y"
{
					if(symbolTable.find(string(yyvsp[-3].str))==symbolTable.end())
					{
						cout<<"Undeclared ID Compiler Error\n";
						exit(0);
					}
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					yyval.number =getFreeIndex();
					string mycode  = string(yyvsp[-3].str)+ '=' + table[yyvsp[-1].number].place + '\n';
					table[yyval.number].code=table[yyvsp[-1].number].code+mycode;
					mainTableIndex=yyval.number;
					;
    break;}
case 17:
#line 270 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '+' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;
					//cout<<table[mainTableIndex].code<<endl;
			      ;
    break;}
case 18:
#line 284 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '-' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;

			      ;
    break;}
case 19:
#line 298 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '*' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;
					//cout<<table[mainTableIndex].code<<endl;
			      ;
    break;}
case 20:
#line 313 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[-1].number].place],symbolTable[table[yyvsp[-1].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					symbolTable[table[yyval.number].place] ="INT";
					table[yyval.number].code = table[yyvsp[-1].number].code +table[yyval.number].place + '=' +string(yyvsp[-3].str)+ '/' + table[yyvsp[-1].number].place+"\n" + string(yyvsp[-3].str) + '=' + table[yyval.number].place;
					mainTableIndex=yyval.number;
			      ;
    break;}
case 21:
#line 333 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{	
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '|' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			     ;
    break;}
case 22:
#line 354 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '&' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 23:
#line 375 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '^' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
				  ;
    break;}
case 24:
#line 396 "first.y"
{
	  				yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[0].number].place]=="BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place]=="INT")
					{
						symbolTable[table[yyval.number].place] ="INT";
					}
					else
					{
						symbolTable[table[yyval.number].place] ="UINT";
					}
					string mygen = '~' + table[yyvsp[0].number].place+"\n";
					table[yyval.number].code = table[yyvsp[0].number].code+table[yyval.number].place + '=' + mygen;
					mainTableIndex=yyval.number;
				  ;
    break;}
case 25:
#line 417 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '+' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 26:
#line 438 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '-' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 27:
#line 461 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '*' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 28:
#line 483 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '/' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 29:
#line 505 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(!checkTypeCompatibility(symbolTable[table[yyvsp[0].number].place],symbolTable[table[yyvsp[0].number].place]))
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[-2].number].place] == "BOOL" ||symbolTable[table[yyvsp[0].number].place] == "BOOL")
					{
						cout<<"Type Incompatible \n";
						exit(0);
					}
					if(symbolTable[table[yyvsp[0].number].place] =="INT"||symbolTable[table[yyvsp[-2].number].place] =="INT")
					symbolTable[table[yyval.number].place] ="INT";
					else
					symbolTable[table[yyval.number].place] ="UINT";
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + '%' + table[yyvsp[0].number].place+"\n";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 30:
#line 526 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp(); 
					if(symbolTable[table[yyvsp[-2].number].place] !="BOOL"||symbolTable[table[yyvsp[0].number].place] !="BOOL")
					{
						cout<<"IncompatibleType\n";
						exit(0);
					}
					
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "||" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 31:
#line 540 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] !="BOOL"||symbolTable[table[yyvsp[0].number].place] !="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "&&" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 32:
#line 553 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + ">=" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 33:
#line 565 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "<=" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 34:
#line 578 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + ">" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 35:
#line 591 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "<" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 36:
#line 604 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatible Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "==" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 37:
#line 616 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[-2].number].place] =="BOOL"||symbolTable[table[yyvsp[0].number].place] =="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[-2].number].code+table[yyvsp[0].number].code +table[yyval.number].place + '=' +table[yyvsp[-2].number].place + "!=" + table[yyvsp[0].number].place+"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 38:
#line 630 "first.y"
{
					yyval.number =getFreeIndex();
					table[yyval.number].place =newtemp();
					if(symbolTable[table[yyvsp[0].number].place] !="BOOL")
					{
						cout<<"Incompatibel Type\n";
						exit(0);
					}
					table[yyval.number].code = table[yyvsp[0].number].code +table[yyval.number].place + '=' + "!" + table[yyvsp[0].number].place +"\n";
					symbolTable[table[yyval.number].place] ="BOOL";
					mainTableIndex=yyval.number;
			      ;
    break;}
case 39:
#line 645 "first.y"
{
					yyval.number = getFreeIndex();
					table[yyval.number] = table[yyvsp[-1].number];
					mainTableIndex = yyval.number;
				  ;
    break;}
case 40:
#line 654 "first.y"
{
	                if(symbolTable.find(string(yyvsp[0].str))==symbolTable.end())
					{
						cout<<"Undeclared ID Compiler Error\n";
						exit(0);
					}
	    			yyval.number =getFreeIndex();
					table[yyval.number].place =string(yyvsp[0].str);
					mainTableIndex=yyval.number;
				  ;
    break;}
case 41:
#line 667 "first.y"
{
	    			yyval.number = getFreeIndex();
					table[yyval.number].place = newtemp();
					symbolTable[table[yyval.number].place]="BOOL";
					table[yyval.number].code = table[yyval.number].place + " = " + "true" + "\n";
					mainTableIndex = yyval.number;
				  ;
    break;}
case 42:
#line 675 "first.y"
{
	    			yyval.number = getFreeIndex();
					table[yyval.number].place = newtemp();
					symbolTable[table[yyval.number].place]="BOOL";
					table[yyval.number].code = table[yyval.number].place + " = " + "false" + "\n";
					mainTableIndex = yyval.number;
				  ;
    break;}
case 43:
#line 683 "first.y"
{
	
						yyval.number = getFreeIndex();
						table[yyval.number].place = newtemp();
						symbolTable[table[yyval.number].place]="INT";
						table[yyval.number].code = table[yyval.number].place + " = " + string(yyvsp[0].str) + "\n";
						mainTableIndex = yyval.number;
				  ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 696 "first.y"




int main()
{
	yyparse();
	cout<<"\n\nGenerated 3-address code : \n\n";

	return 0;
}
